// <auto-generated />
namespace RedeSocialAT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class jdhbfreeueresddiddlrdrerererererdn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jdhbfreeueresddiddlrdrerererererdn));
        
        string IMigrationMetadata.Id
        {
            get { return "202212222221182_jdhbfreeueresddiddlrdrerererererdn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
